from . import starthandler
from . import users_handler
from . import item_handler
from . import add_item_ADMIN
from . import info_handler
from . import oformit_zakaz
from . import my_basket
from . import inline_handler
from . import contact_us_handler
from . import history_handler
from . import promokods_handler
from . import settings_handler
from . import history_handler_ADMIN
